version: '3.4'

services:
  mssql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-server
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: ${MSSQL_SA_PASSWORD}
    ports:
      - "1433:1433"
 
  AGSR.Patients:
    image: ${DOCKER_REGISTRY-}agsr-patients
    container_name: agsr-patients
    build:
      context: .
      dockerfile: AGSR.Patients/Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      ASPNETCORE_URLS: https://+:443;http://+:80
      ASPNETCORE_HTTPS_PORT: 443
      ASPNETCORE_Kestrel__Certificates__Default__Path: /etc/ssl/certs/agsr_cert.pfx
      ASPNETCORE_Kestrel__Certificates__Default__Password: ${SSL_CERTIFICATE_PASSWORD}
      MSSQL_SERVER: mssql-server
      MSSQL_DATABASE: AGSR.PatientDb
      MSSQL_USER: sa
      MSSQL_PASSWORD: ${MSSQL_SA_PASSWORD}
    depends_on:
      - mssql-server
    volumes:
      - ./Certificates:/etc/ssl/certs
  
  agsr.client:
    image: ${DOCKER_REGISTRY-}agsr-client
    container_name: agsr-client
    build:
      context: .
      dockerfile: AGSR.Client/Dockerfile
    environment:
      PATIENTS_API_URL: http://agsr-patients:80
    depends_on:
      - AGSR.Patients
